### ISSUE TITLE
DataNose - Teams connector

### ISSUE THREAD

**Issue by msokolewicz** [UvA-FNWI/DataNose-planning#1]
### Description
The UvA has been using Microsoft Teams since the summer of 2020. Teams are often organized based on existing groups of people, for instance lecturers in a certain course, or an examinations board. Since administration of these real life teams happens in DataNose, we should allow DataNose to communicate with Teams and allow adding and removing people from these Teams.teams automatically.

### Todo list
- [x] Create intermediate connector interface, allowing the following actions:
  - [x] Create a new Team
  - [x] Add/remove users from a team
  - [x] Invite new guest users to a team
- [x] Create an overview page to link users to user roles in datanose
- [ ] Link the new teams to the programme overview page in datanose

### Deadline
Q4 2020
